import Head from 'next/head';

const Admin = () => {
  return (
    <div>
      <Head>
        <title>Admin page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Admin test</h1>
    </div>
  );
};

export default Admin;
