import Head from 'next/head';
import Image from 'next/image';
// import styles from '../styles/Home.module.css'

const Market = () => {
  return (
    <div>
      <Head>
        <title>Market page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Market test</h1>
    </div>
  );
};

export default Market;
